Exchanges = {
    ''    : 'Undefined',
    'ARCX': 'New York Stock Exchange Archipelago',
    'BATS': 'Bats Global Markets is a global stock exchange operator based in Lenexa, Kansas, with additional offices in London, New York, Chicago, and Singapore',
    'BVMF': 'Undefined',
    'DSMD': 'Undefined',
    'FMTS': 'MTS France SAS',
    'MISX': 'Undefined',
    'OOTC': 'Over-the-counter (OTC) refers to the process of how securities are traded via a broker-dealer network as opposed to on a centralized exchange',
    'WBAH': 'Vienna Stock Exchange',
    'XAMS': 'Euronext Amsterdam',
    'XASE': 'American Stock Exchange',
    'XASX': 'Australian Stock Exchange',
    'XBER': 'Borse Berlin',
    'XBKK': 'Stock Exchange of Thailand',
    'XBOM': 'Bombay Stock Exchange',
    'XBRU': 'Euronext Brussels',
    'XETR': 'Xetra Stock Exchange',
    'XFRA': 'Deutsche Boerse AG',
    'XHKG': 'The Stock Exchange of Hong Kong Limited',
    'XIDX': 'Indonesia Stock Exchange',
    'XJAS': 'JASDAQ Securities Exchange',
    'XKAR': 'Karachi Stock Exchange',
    'XKLS': 'Kuala Lumpur Stock Exchange',
    'XKRX': 'Korea Stock Exchange',
    'XLON': 'London Stock Exchange',
    'XNAS': 'NASDAQ',
    'XNGO': 'Nagoya Stock Exchange',
    'XNGS': 'NASDAQ GS',
    'XNYS': 'New York Stock Exchange',
    'XNZE': 'New Zealand Exchange',
    'XOSE': 'Osaka Securities Exchange',
    'XOSL': 'Oslo Stock Exchange',
    'XPAR': 'Euronext Paris',
    'XSES': 'Singapore Exchange Securities Trading Limited',
    'XSHE': 'Shenzhen Stock Exchange',
    'XSHG': 'Shanghai Stock Exchange',
    'XSTC': 'Hochiminh Stock Exchange',
    'XSTO': 'Stockholm Stock Exchange',
    'XSWX': 'Swiss Exchange',
    'XTAI': 'Taiwan Stock Exchange',
    'XTKS': 'Tokyo Stock Exchange',
    'XVTX': 'Six Swiss Exchange',
    'YYYY': 'All German Stock Exchanges'}
